FROM python:3.10.12-alpine3.18

RUN apk update
RUN apk add \
    curl \
    unzip \
    git \
    zip

#Install aws
RUN curl --create-dirs -O --output-dir /tmp "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip /tmp/awscli-exe-linux-x86_64.zip -d /tmp && \
    /tmp/aws/install --bin-dir /bin --install-dir /aws-cli

RUN pip install aws-sam-cli

RUN git config --global --add safe.directory /portal/backend